from __future__ import annotations

DOMAIN_CONFIGS = {
    "tech_development": {
        "resource_sources": ["github", "gitlab", "stack_overflow", "mdn", "w3schools", "freecodecamp", "official_docs"],
        "project_verbs": ["build", "code", "create", "implement", "deploy", "test", "debug"],
        "video_keywords": ["tutorial", "code along", "walkthrough", "demo", "build", "step by step"],
        "success_criteria": ["runs without errors", "passes tests", "deployed", "code reviewed"],
        "resource_fetcher": "fetch_github_repos",
        "graph_style": "Use a toolchain-aware progression tied to the learning goal.",
        "project_action": "build or implement",
        "search_verbs": ["tutorial", "explained", "real world example"],
    },
    "creative_arts": {
        "resource_sources": ["youtube", "pinterest", "instructables", "wikihow", "skillshare_articles", "craft_blogs", "recipe_sites"],
        "project_verbs": ["create", "make", "prepare", "practice", "follow", "complete", "photograph", "document"],
        "video_keywords": ["demonstration", "step by step", "technique", "how to", "beginner guide", "example", "process"],
        "success_criteria": ["completed artifact", "can explain process", "recreated technique", "photo documentation"],
        "resource_fetcher": "fetch_youtube_channels",
        "graph_style": "Use process steps such as materials, setup, practice, feedback, revision, and finished work.",
        "project_action": "create or practice",
        "search_verbs": ["step by step", "beginner guide", "practice"],
    },
    "business_professional": {
        "resource_sources": ["hbr", "ted_talks", "linkedin_learning", "mit_sloan", "coursera_business", "forbes", "mckinsey", "podcasts"],
        "project_verbs": ["prepare", "deliver", "write", "present", "role play", "record", "analyze"],
        "video_keywords": ["case study", "example", "real world", "technique", "framework", "how to handle", "best practices"],
        "success_criteria": ["recorded yourself", "peer feedback", "applied framework", "written reflection"],
        "resource_fetcher": "fetch_articles_and_podcasts",
        "graph_style": "Use scenario, preparation, rehearsal, delivery, feedback, and refinement steps.",
        "project_action": "prepare or deliver",
        "search_verbs": ["best practices", "example", "scenario"],
    },
    "health_wellness": {
        "resource_sources": ["pubmed_simplified", "mayo_clinic", "nhs", "healthline", "yoga_journal", "meditation_apps_free", "nih_guides"],
        "project_verbs": ["follow", "practice", "log", "complete", "track", "prepare", "schedule"],
        "video_keywords": ["follow along", "guided", "routine", "practice", "beginner friendly", "safe form", "30 day"],
        "success_criteria": ["completed practice", "logged consistency", "can demonstrate form", "reflection written"],
        "resource_fetcher": "fetch_health_resources",
        "graph_style": "Use safety, foundation, routine, tracking, adjustment, and consistency steps.",
        "project_action": "practice or log",
        "search_verbs": ["beginner", "routine", "how to"],
    },
    "academic_learning": {
        "resource_sources": ["khan_academy", "crash_course", "mit_ocw", "stanford_encyclopedia", "project_gutenberg", "arxiv_simplified", "jstor_daily"],
        "project_verbs": ["write", "explain", "create", "diagram", "teach", "answer", "summarize"],
        "video_keywords": ["explanation", "lecture", "introduction to", "overview", "simplified", "animated", "visual"],
        "success_criteria": ["can explain in own words", "answered questions", "connected to prior knowledge", "real world example"],
        "resource_fetcher": "fetch_academic_resources",
        "graph_style": "Use foundations, core concepts, worked examples, practice, and synthesis steps.",
        "project_action": "analyze or explain",
        "search_verbs": ["lecture", "overview", "examples"],
    },
    "life_skills": {
        "resource_sources": ["wikihow", "the_balance_careers", "ask_a_manager", "consumer_reports", "family_education", "cdc_parenting", "youtube_how_to", "reddit_wikis"],
        "project_verbs": ["complete", "create", "prepare", "simulate", "practice", "organize", "fix"],
        "video_keywords": ["how to", "fix", "prepare", "manage", "organize", "complete guide", "walkthrough", "real example"],
        "success_criteria": ["task completed", "template saved", "simulated scenario passed", "checklist fully checked"],
        "resource_fetcher": "fetch_life_skills_resources",
        "graph_style": "Use setup, safety, step-by-step practice, troubleshooting, and independent completion steps.",
        "project_action": "complete or prepare",
        "search_verbs": ["step by step", "checklist", "how to"],
    },
    "humanities": {
        "resource_sources": ["smarthistory", "imdb_analysis", "met_museum", "youtube_analysis_channels", "coursera_arts"],
        "project_verbs": ["analyze", "create", "imitate", "compare", "interpret", "discuss", "write"],
        "video_keywords": ["analysis", "breakdown", "appreciation", "history of", "technique", "close reading", "masterwork"],
        "success_criteria": ["written analysis", "original piece created", "techniques identified", "peer discussion notes"],
        "resource_fetcher": "fetch_humanities_resources",
        "graph_style": "Use context, vocabulary, methods, close reading or analysis, comparison, and interpretation steps.",
        "project_action": "analyze or interpret",
        "search_verbs": ["analysis", "overview", "interpretation"],
    },
}
